export const TOGGLE_SETTINGS_PANE = 'TOGGLE_SETTINGS_PANE';
export const TOGGLE_SIDEBAR_MENU = 'TOGGLE_SIDEBAR_MENU';
export const SET_ACTIVE_MENU_ON_SIDEBAR = 'SET_ACTIVE_MENU_ON_SIDEBAR';
export const SET_CURRENT_LANGUAGE = 'SET_CURRENT_LANGUAGE';
